### ISSUE TITLE
Already-followed.csv not getting written

### ISSUE THREAD

**Issue by marcfielding1** [rhiever/twitter-follow-bot#18]
Heya,

Just a quick one I can't see to get this to write out to the CSV file, the CSV filename I specified was "./already-followed.csv"

Any ideas?

Cheers

Marc

**Comment by Yomb** [comment]
Hi, just add

out_file = open(ALREADY_FOLLOWED_FILE, "a")
out_file.write(str(tweet["user"]["id"]) + "\n")
out_file.close()

before

print("followed %s" % (tweet["user"]["screen_name"]))

in auto_follow function (for example)

**Comment by marcfielding1** [comment]
I think it was a file permissions issue, all sorted now

**Comment by GarlandM** [comment]
What was the issue? I'm having the same problem.

**Comment by marcfielding1** [comment]
Hi Garland, sorry i've been away. To be honest i'm not entirely sure what happened I think it might have been a permissions issue although no error was thrown. It simply worked after I moved everything to a new folder. I'm working on a fork that does all this off a MySQL database so i'll let you know once i've had time to finish it!

**Comment by alexmilesyounger** [comment]
Hi all, 

I'm getting the same issue, where already-followed.txt is not getting written. Every time I check it, it's empty. Any help here would be appreciated. 

I'm running this as a worker on Heroku, instead of as a cron job as suggested (https://github.com/rhiever/TwitterFollowBot/issues/37). Maybe Heroku is causing problems? 

Cheers,
Alex

**Comment by rhiever** [comment]
Are any of the text files being written?

**Comment by JSTQ** [comment]
followers and following is written, already-followed is empty

**Comment by alexmilesyounger** [comment]
Yes, as JSTQ said, followers.txt and following.txt are being written, but already-followed.txt is empty. 

I cloned the latest version of the repo four days ago and pushed it to my server. Adding a random time between following users is a nice touch, btw.

**Comment by rhiever** [comment]
`already-followed.txt` doesn't get written until you run the `auto_unfollow` method. The reasoning behind this is that the list is only meant to track users that the bot has followed, they didn't follow back, and then the bot unfollowed them. This way, the bot won't bother those people by following them again.

**Comment by alexmilesyounger** [comment]
That makes sense, but I'm running the auto_unfollow on a regular basis, and my already-followed.txt is still blank. I'm still pretty new to Python and Github, but if I can help I'd love to jump in. I'm just a bit lost as to what exactly isn't working.

**Comment by marcfielding1** [comment]
Can't remember if I replied but check your write permissions for the user that's running the process. 

I keep meaning to finish the MySQL version of this I was doing.

**Comment by rhiever** [comment]
@alexmilesyounger: As @marcfielding1 said, I can only think that it's some sort of permissions issue. Although it's strange that two files are written but not that one. This is a difficult thing to debug without looking at your setup directly.

@marcfielding1: That's neat to hear that you're developing a SQL version -- I think that could be quite useful to store the data in a relational database. Although I wonder if using some sort of relational database that doesn't require a server would be better? e.g., sqlite.

**Comment by marcfielding1** [comment]
I suppose that could be included as an option - I could include MySQL, sql lite and even some nosql db's although the latter should probably look at recording a bit more info!

**Comment by rhiever** [comment]
My main concern when managing this project is to keep the bot relatively
easy to use. Someone tried to a commit a MySQL version in the past, but
such an implementation required too much setup on the user end. Hence the
preference for flat files that the user only needs to point the bot to
without any additional setup.

On Monday, July 20, 2015, marcfielding1 <notifications@github.com> wrote:

> I suppose that could be included as an option - I could include MySQL, sql
> lite and even some nosql db's although the latter should probably look at
> recording a bit more info!
>
> Sent from my iPhone
>
> > On 20 Jul 2015, at 15:40, Randy Olson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > @alexmilesyounger: As @marcfielding1 said, I can only think that it's
> some sort of permissions issue. Although it's strange that two files are
> written but not that one. This is a difficult thing to debug without
> looking at your setup directly.
> >
> > @marcfielding1: That's neat to hear that you're developing a SQL version
> -- I think that could be quite useful to store the data in a relational
> database. Although I wonder if using some sort of relational database that
> doesn't require a server would be better? e.g., sqlite.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/18#issuecomment-123005567>
> .
>


-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by marcfielding1** [comment]
Hmm if I created a class that allowed you to decide by simply adding host and credentials would that be ok?

to use MySQL do:

$bot->mySqlInit(host,user,pass)

Flat file
$bot->sqlLiteInit(....)

Obviously would create tables and indexes if needed.

**Comment by marcfielding1** [comment]
Sorry that was pseudo php but you get the idea

**Comment by rhiever** [comment]
That could work.

On Mon, Jul 20, 2015 at 4:08 PM, marcfielding1 <notifications@github.com>
wrote:

> Hmm if I created a class that allowed you to decide by simply adding host
> and credentials would that be ok?
>
> to use MySQL do:
>
> $bot->mySqlInit(host,user,pass)
>
> Flat file
> $bot->sqlLiteInit(....)
>
> Obviously would create tables and indexes if needed.
>
> Sent from my iPhone
>
> > On 20 Jul 2015, at 15:52, Randy Olson <notifications@github.com> wrote:
> >
> > My main concern when managing this project is to keep the bot relatively
> > easy to use. Someone tried to a commit a MySQL version in the past, but
> > such an implementation required too much setup on the user end. Hence
> the
> > preference for flat files that the user only needs to point the bot to
> > without any additional setup.
> >
> > On Monday, July 20, 2015, marcfielding1 <notifications@github.com>
> wrote:
> >
> > > I suppose that could be included as an option - I could include MySQL,
> sql
> > > lite and even some nosql db's although the latter should probably look
> at
> > > recording a bit more info!
> > >
> > > Sent from my iPhone
> > >
> > > > On 20 Jul 2015, at 15:40, Randy Olson <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > >
> > > > @alexmilesyounger: As @marcfielding1 said, I can only think that
> it's
> > > some sort of permissions issue. Although it's strange that two files
> are
> > > written but not that one. This is a difficult thing to debug without
> > > looking at your setup directly.
> > > >
> > > > @marcfielding1: That's neat to hear that you're developing a SQL
> version
> > > -- I think that could be quite useful to store the data in a
> relational
> > > database. Although I wonder if using some sort of relational database
> that
> > > doesn't require a server would be better? e.g., sqlite.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/rhiever/TwitterFollowBot/issues/18#issuecomment-123005567>
>
> > > .
> > >
> >
> >
> > --
> > Randal S. Olson, Ph.D.
> > Postdoctoral Researcher, Institute for Biomedical Informatics
> > University of Pennsylvania
> >
> > E-mail: rso@randalolson.com | Twitter: @randal_olson
> > <https://twitter.com/randal_olson>
> > http://www.randalolson.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/18#issuecomment-123014078>
> .
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com
