### ISSUE TITLE
Support for multiple twitter accounts

### ISSUE THREAD

**Issue by pkayfire** [rhiever/twitter-follow-bot#20]
I'm thinking about adding support for multiple twitter accounts. Would first probably start by detaching the configuration in twitter_follow_bot #L25-29. Thoughts all?

**Comment by ydaniels** [comment]
Actually you don't need any authentication.txt Twitter does not support basic auth to its api anymore so you can't use your password and username to make request .I  have edited the code to support multiple accounts but I stopped using it.
What the new user would have to do is anytime they want to add an account they would implement a oauth flow request to Twitter with their consumer keys and Twitter would send a auth url which the user would open in their browser and login and authorize the app. Twitter would now redirect them to their redirect url which they can get thier token verifier in exchange for their tokens which can be stored, so anytime you need to perform an action just load the tokens for the particular account that's all but the consumer key remains the Same . Very simple everything can be automated.

**Comment by kylepierce** [comment]
In my twitter_info.py file I just have have my two account's info. I comment out the one I am not using and leave the other one readable. It has worked for me. I think you could do it for multiple accounts.

**Comment by rhiever** [comment]
I just committed a major change to the repo that now allows the bot to support multiple accounts through the use of separate config files.
