### ISSUE TITLE
Unfollow Limit

### ISSUE THREAD

**Issue by BradHouston** [rhiever/twitter-follow-bot#24]
Is there a way to set a limit on how many people you Unfollow? because I just had my app banned due to mass unfollow! I'd like to keep it at around 700

**Comment by ydaniels** [comment]
just put a break statement when it gets to 700
you can set a counter to 0 and increase it as you unfollow.
e.g
counter=0
for loop:
      if counter==700:
            print 'done'
            break
      unfollowfunction
      counter+=1

**Comment by BradHouston** [comment]
Where would this go in the code?

**Comment by ydaniels** [comment]
In this function 'def auto_unfollow_nonfollowers ():'
goto line 210 you'll see the for loop just put the code '''counter = 0
             for  user_id in not_following_back:
              if counter==700:
                      print 'done'
                      break
              (every other codes)
               counter=counter+1

**Comment by ydaniels** [comment]
Sorry I didn't use mark down for the codes in previous comment i would edit it when I get on my system

**Comment by ydaniels** [comment]
ok have you done it, if not tell me so I can write it so you'll just copy and paste it

**Comment by BradHouston** [comment]
I couldn't find a way im afraid!

**Comment by ydaniels** [comment]
Simply replace the code from line 210 to 213 with this
```
counter=0     
for user_id in not_following_back:
    if counter==700:#change this number to limit number of unfollowed user 
        print 'done  ' 
        break
    if user_id not in users_keep_following:
        t.friendships.destroy(user_id=user_id)
        print("unfollowed %d" % (user_id))
        count=count+1
```

**Comment by rhiever** [comment]
@BradHouston, did you get this working? @ydaniels has been right on point.

**Comment by BradHouston** [comment]
I have installed it, just testing now.
