### ISSUE TITLE
Stacking actions

### ISSUE THREAD

**Issue by kylepierce** [rhiever/twitter-follow-bot#27]
I have been trying to understand the psychology of why people follow random accounts on twitter. I am interested in seeing if people are more willing to follow people back if there are multiple actions instead of one. It is pretty common to get a favorite on status that includes SEO or whatever keyword. So what I am interested in doing is have the bot follow people based on who they follow, but after they follow them it favorites a random tweet range [0...20] or multiple tweets. I have done this with instagram and I got pretty good results. In the future it would be cool to log results and calculate conversion based on main account scraped from, but thats another time.

So what I am wondering is what variable do I use to favorite a tweet of the user I just followed? I only see the user id.

**Comment by kylepierce** [comment]
I am a new programmer so this code probably not perfect but it works for me :) 

```                user_tweets = t.statuses.user_timeline(user_id=user_id)
                last_tweet = user_tweets[0]
                result = t.favorites.create(_id=last_tweet["id"])

                print("Favorite their tweet: %s" % (result["text"].encode("utf-8")))
```

**Comment by rhiever** [comment]
That looks right. So you could do something like:
    
    import random

    num_tweets = random.randint(0, 20)
    user_tweets = t.statuses.user_timeline(user_id=user_id)
    for tweet_index in range(num_tweets):
        result = t.favorites.create(_id=user_tweets[tweet_index]["id"])
        print("Favorited their tweet: %s" % (result["text"].encode("utf-8")))
