### ISSUE TITLE
Rate Limit Support

### ISSUE THREAD

**Issue by selimanac** [rhiever/twitter-follow-bot#29]
Rate Limit support would be fine

**Comment by rhiever** [comment]
:+1: I agree that keeping track of how many requests are sent and more gracefully managing the rate limits of the API would be a great enhancement. This enhancement could be as simple as detecting the "you are rate limited" error from the API and gracefully closing the bot.

**Comment by princeasfi** [comment]
Hi Rhiever, im new on here, I already installed git bash and clone this project using git clone command , what should i do next to use this twitter follower bot, can u provide a tutorial of each step and commands?

**Comment by selimanac** [comment]
Also (as far as i know) Rate Limit Error returns the time which you have to wait until next request. (I have a few cron jobs which runs your script. Today twitter stops my api write access :))

**Comment by Nickfost** [comment]
Twitter pulled all my API access too. It was on April first so i was hoping it was a joke, alas it was not. :cry:

**Comment by rhiever** [comment]
@Nickfost: I'm working on a patch to make the bot more gracefully quit upon hitting rate limits, but not abusing the API is up to the user. Either spread your usage of the bot evenly along the day, or only use the bot en masse a couple times a day. I've also seen people get their access revoked if they are being "spammy" with their tweets, e.g., constantly promoting their business/products.
