### ISSUE TITLE
Add a method to perform a post

### ISSUE THREAD

**Issue by teopost** [rhiever/twitter-follow-bot#33]
Add a method to perform a post

**Comment by rhiever** [comment]
:+1: This is far outside my personal use case for the bot, so I likely won't develop this feature, but I encourage someone to develop it and send in a PR.

If you'd like a good code base to start with, I have a separate bot that posts to Twitter here: https://github.com/rhiever/reddit-twitter-bot/blob/master/reddit_twitter_bot.py

**Comment by teopost** [comment]
OK @rhiever. Thanks
